on: push
name: Build/Deploy
jobs:
  mavenBuild:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Maven build
        uses: xlui/action-maven-cli/jdk8@master
        with:
          args: clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: If master branch
        uses: actions/bin/filter@master
        with:
          args: branch master
      - name: Google Cloud SDK auth
        uses: freddyboucher/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Google Cloud SDK deploy
        uses: freddyboucher/gcloud/cli@master
        with:
          args: --quiet --verbosity=warning --project=gwt-oauth2 app deploy sample/sample-server/target/sample-server-0.4-SNAPSHOT
            --promote --version=0-4-snapshot
